version: '3'

services:
  web:
    build: .
    image: django-app
    command: [
      "python", "manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - "0.0.0.0:8000:8000"
    depends_on: 
      - db
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
      POSTGRES_HOST: db

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
